Repository ModelEngine-Group/app-platform, pull requests merged in 2025-04, with the labels that each got.

#1 [app-engine] 修改工作流模板的结束节点的 finalOutput 结构
  app-builder/jane/jober/sql/jade/06_appbuilder_insert.sql
Labels: type: bug, in: builder

#2 [frontend] 优化前端报错提示信息
  app-engine/frontend/src/locale/en_US.json
  app-engine/frontend/src/locale/zh_CN.json
Labels: in: builder, type: enhancement

#3 [app-builder] 处理任务兼容插件在表单场景的问题
  app-builder/jane/jober/sql/jade/02_appbuilder_create.sql
  app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/service/impl/AippRunTimeServiceImpl.java
  app-builder/jane/task-new/src/main/java/modelengine/fit/task_new/converter/ConvertorUtils.java
  app-builder/jane/task-new/src/main/java/modelengine/fit/task_new/entity/MetaInstance.java
  app-builder/jane/task-new/src/main/java/modelengine/fit/task_new/po/MetaInstancePo.java
Labels: type: bug, in: builder

#5 [store] 修复删除 Http 插件异常报错问题
  store/plugins/store-tool-uploader/src/main/java/modelengine/jade/store/tool/upload/service/impl/PluginUploadServiceImpl.java
Labels: type: bug, in: store

#10 [app-builder] 增加 StaticResourceFilter 过滤器是否启用的开关
  common/plugins/http-interceptor/src/main/java/modelengine/jade/common/filter/support/StaticResourceFilter.java
  common/plugins/http-interceptor/src/main/resources/application.yml
Labels: in: builder, type: enhancement

#15 [frontend] 修复发布公告富文本编辑器工具栏没显示问题
  app-engine/frontend/src/pages/components/text-editor.tsx
Labels: type: bug, in: builder

#17 [frontend] 修复白屏的问题
  app-engine/frontend/src/pages/components/text-editor.tsx
Labels: type: bug, in: builder

#18 [app-builder] 创建应用模板结束节点添加默认的 enableLog 结构
  app-builder/jane/jober/sql/jade/06_appbuilder_insert.sql
Labels: type: bug, in: builder

#20 [app-platform] 增加 README 文件
  README.md
Labels: in: builder, type: documentation

#19 [app-builder] 添加开始节点应用配置相关国际化
  app-engine/frontend/src/assets/images/appConfig/chat-screenshot.jpg
  app-engine/frontend/src/assets/images/appConfig/heatmap-screenshot.jpg
  app-engine/frontend/src/locale/en_US.json
  app-engine/frontend/src/locale/zh_CN.json
  app-engine/frontend/src/pages/addFlow/config.ts
Labels: in: builder, type: enhancement

#37 [app-platform] 添加 app-platform 的 github action 文件
  .github/workflows/app-platform-java-compile.yml
Labels: in: builder, type: task

#39 新增开源社区用户角色
  common/plugins/appengine-oms-adapter/src/main/resources/api/common.json
  common/plugins/appengine-oms-adapter/src/main/resources/api/rest-service-aipp.json
  common/plugins/appengine-oms-adapter/src/main/resources/api/rest-service-appBuilder.json
  common/plugins/appengine-oms-adapter/src/main/resources/api/rest-service-eval.json
  common/plugins/appengine-oms-adapter/src/main/resources/api/rest-service-metrics.json
  common/plugins/appengine-oms-adapter/src/main/resources/api/rest-service-northApi.json
  common/plugins/appengine-oms-adapter/src/main/resources/api/rest-service-store.json
  common/plugins/appengine-oms-adapter/src/main/resources/menu/preset_menu_data.json
  common/plugins/appengine-oms-adapter/src/main/resources/role/preset_role.json
  common/plugins/appengine-oms-adapter/src/main/resources/role/preset_role_i18n.json
Labels: in: carver, type: task

#40 [app-platform] 修复应用配置插件点击没有正确跳转问题
  app-engine/frontend/src/locale/zh_CN.json
  app-engine/frontend/src/pages/configForm/configUi/components/skill-list.tsx
Labels: type: bug, in: builder

#42 [app-builder] 创建应用助手和智能体时结束节点添加默认的 enableLog 结构
  app-builder/jane/jober/sql/jade/06_appbuilder_insert.sql
Labels: type: bug, in: builder

#41 [app-builder] 优化部分性能，添加流程数据定时清理机制
  app-builder/fel/java/pom.xml
  app-builder/jane/dynamic-form-genericable/pom.xml
  app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/fitable/FlowPublishSubscriber.java
  app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/service/impl/AippRunTimeServiceImpl.java
  app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/service/impl/AppChatServiceImpl.java
  app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/util/CacheUtils.java
  app-builder/jane/services/aipp-service/src/main/java/modelengine/fit/jober/aipp/dto/chat/CreateAppChatRequest.java
  app-builder/plugins/plugins-show-case-parent/agent-test/pom.xml
  app-builder/plugins/plugins-show-case-parent/fortune-telling/pom.xml
  app-builder/plugins/plugins-show-case-parent/wenjie-data/pom.xml
  app-builder/waterflow/java/pom.xml
  app-builder/waterflow/java/waterflow-dependency/pom.xml
  app-builder/waterflow/java/waterflow-service/src/main/java/modelengine/fit/waterflow/common/utils/UuidUtils.java
  app-builder/waterflow/java/waterflow-service/src/main/java/modelengine/fit/waterflow/flowsengine/biz/service/scheduletasks/CleanContextSchedule.java
  app-builder/waterflow/java/waterflow-service/src/main/java/modelengine/fit/waterflow/flowsengine/domain/flows/context/repo/flowcontext/FlowContextPersistRepo.java
  app-builder/waterflow/java/waterflow-service/src/main/java/modelengine/fit/waterflow/flowsengine/domain/flows/context/repo/flowcontext/FlowContextRepo.java
  app-builder/waterflow/java/waterflow-service/src/main/java/modelengine/fit/waterflow/flowsengine/domain/flows/context/repo/flowtrace/DefaultFlowTraceRepo.java
  app-builder/waterflow/java/waterflow-service/src/main/java/modelengine/fit/waterflow/flowsengine/domain/flows/context/repo/flowtrace/FlowTraceRepo.java
  app-builder/waterflow/java/waterflow-service/src/main/java/modelengine/fit/waterflow/flowsengine/persist/mapper/FlowContextMapper.java
  app-builder/waterflow/java/waterflow-service/src/main/java/modelengine/fit/waterflow/flowsengine/persist/mapper/FlowTraceMapper.java
  app-builder/waterflow/java/waterflow-service/src/main/java/modelengine/fit/waterflow/flowsengine/utils/OhScriptExecutor.java
  app-builder/waterflow/java/waterflow-service/src/main/resources/application.yml
  app-builder/waterflow/java/waterflow-service/src/main/resources/mapper/FlowContextMapper.xml
  app-builder/waterflow/java/waterflow-service/src/main/resources/mapper/FlowTraceMapper.xml
  app-builder/waterflow/java/waterflow-service/src/test/java/modelengine/fit/waterflow/flowsengine/persist/mapper/FlowContextMapperTest.java
  app-builder/waterflow/java/waterflow-service/src/test/java/modelengine/fit/waterflow/flowsengine/persist/mapper/FlowTraceMapperTest.java
  app-engine/plugins/app-metrics/pom.xml
  common/components/ui-word-globalizer/pom.xml
  common/dependency/pom.xml
  pom.xml
Labels: in: builder, type: enhancement

#44 [app-builder] 修改国际化中的中文描述
  app-engine/frontend/src/locale/zh_CN.json
Labels: in: builder, type: enhancement

#43 [app-builder] 头像上传url前缀配置化
  app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/service/impl/AppBuilderAppServiceImpl.java
  app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/util/AppImExportUtil.java
  app-builder/jane/plugins/aipp-plugin/src/main/resources/application-prod.yml
  app-builder/jane/plugins/aipp-plugin/src/test/java/modelengine/fit/jober/aipp/service/AppBuilderAppServiceImplTest.java
  app-builder/jane/plugins/aipp-plugin/src/test/java/modelengine/fit/jober/aipp/service/impl/AppTemplateServiceImplTest.java
  app-builder/jane/plugins/aipp-plugin/src/test/java/modelengine/fit/jober/aipp/util/AppImExportUtilTest.java
Labels: in: builder, type: enhancement

#47 [app-builder] 个人 PC x86 包问题修复代码修改
  app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/controller/FileController.java
  app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/service/impl/AppBuilderAppServiceImpl.java
  app-engine/frontend/src/components/layout/index.tsx
  app-engine/frontend/src/pages/aippIndex/index.tsx
  app-engine/frontend/src/router/route.ts
Labels: type: bug, in: builder

#46 [frontend] 应用使能上传自定义插件失败问题修复
  app-engine/frontend/src/components/plugin-card/index.tsx
  app-engine/frontend/src/locale/en_US.json
  app-engine/frontend/src/locale/zh_CN.json
  app-engine/frontend/src/pages/appDev/index.tsx
  app-engine/frontend/src/pages/chatPreview/components/send-editor/components/recommends.tsx
  app-engine/frontend/src/pages/chatPreview/index.tsx
  app-engine/frontend/src/pages/configForm/configUi/components/recommend.tsx
  app-engine/frontend/src/pages/detailFlow/index.tsx
  app-engine/frontend/src/pages/helper.ts
  app-engine/frontend/src/styles/common.scss
Labels: type: bug, in: builder

#51 [app-builder] 修改应用模板sql
  app-builder/jane/jober/sql/jade/06_appbuilder_insert.sql
Labels: in: builder, type: task

#53 [app-builder] 修复启动报错问题
  app-builder/fel/java/pom.xml
  app-builder/jane/dynamic-form-genericable/pom.xml
  app-builder/plugins/plugins-show-case-parent/agent-test/pom.xml
  app-builder/plugins/plugins-show-case-parent/fortune-telling/pom.xml
  app-builder/plugins/plugins-show-case-parent/wenjie-data/pom.xml
  app-builder/waterflow/java/pom.xml
  app-builder/waterflow/java/waterflow-dependency/pom.xml
  app-engine/plugins/app-metrics/pom.xml
  common/components/ui-word-globalizer/pom.xml
  common/dependency/pom.xml
  pom.xml
Labels: type: bug, in: builder

#52 [frontend] 清空页面聊天记录时添加报错提示
  app-engine/frontend/src/pages/chatPreview/components/send-editor/components/editor-btn-home.tsx
Labels: in: builder, type: enhancement

#50 [app-builder] 优化大模型调用报错信息
  app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/common/exception/AippErrCode.java
  app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/fitable/AippFlowExceptionHandle.java
  app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/fitable/LlmComponent.java
  app-builder/jane/plugins/aipp-plugin/src/main/resources/i18n/messages_en.properties
  app-builder/jane/plugins/aipp-plugin/src/main/resources/i18n/messages_zh.properties
  app-builder/jane/services/aipp-service/src/main/java/modelengine/fit/jober/aipp/common/exception/AippErrCode.java
Labels: in: builder, type: enhancement

#86 [app-builder] 智能表单查询接口不返回内置表单
  app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/condition/FormQueryCondition.java
  app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/service/impl/AppBuilderFormServiceImpl.java
  app-builder/jane/plugins/aipp-plugin/src/main/resources/application-prod.yml
  app-builder/jane/plugins/aipp-plugin/src/main/resources/mapper/AppBuilderFormMapper.xml
  app-builder/jane/plugins/aipp-plugin/src/test/java/modelengine/fit/jober/aipp/service/AppBuilderFormServiceImplTest.java
Labels: type: bug, in: builder

#38 [app-builder] 新增用户对于模型列表增删改查接口
  app-builder/plugins/aipp-custom-model-center/pom.xml
  app-builder/plugins/aipp-custom-model-center/src/main/java/modelengine/fit/jade/aipp/model/mapper/ModelMapper.java
  app-builder/plugins/aipp-custom-model-center/src/main/java/modelengine/fit/jade/aipp/model/mapper/UserModelMapper.java
  app-builder/plugins/aipp-custom-model-center/src/main/java/modelengine/fit/jade/aipp/model/po/ModelPo.java
  app-builder/plugins/aipp-custom-model-center/src/main/java/modelengine/fit/jade/aipp/model/po/UserModelDetailPo.java
  app-builder/plugins/aipp-custom-model-center/src/main/java/modelengine/fit/jade/aipp/model/po/UserModelPo.java
  app-builder/plugins/aipp-custom-model-center/src/main/java/modelengine/fit/jade/aipp/model/repository/UserModelRepo.java
  app-builder/plugins/aipp-custom-model-center/src/main/java/modelengine/fit/jade/aipp/model/repository/impl/UserModelRepoImpl.java
  app-builder/plugins/aipp-custom-model-center/src/main/java/modelengine/fit/jade/aipp/model/service/impl/CustomAippModelCenter.java
  app-builder/plugins/aipp-custom-model-center/src/main/java/modelengine/fit/jade/aipp/model/service/impl/UserModelConfigService.java
  app-builder/plugins/aipp-custom-model-center/src/main/resources/mapper/ModelMapper.xml
  app-builder/plugins/aipp-custom-model-center/src/main/resources/mapper/UserModelMapper.xml
  app-builder/plugins/aipp-custom-model-center/src/test/java/modelengine/fit/jade/aipp/model/service/impl/CustomAippModelCenterTest.java
  app-builder/plugins/aipp-custom-model-center/src/test/java/modelengine/fit/jade/aipp/model/service/impl/UserModelConfigServiceTest.java
  app-builder/services/aipp-model-center/pom.xml
  app-builder/services/aipp-model-center/src/main/java/modelengine/fit/jade/aipp/model/dto/UserModelDetailDto.java
  app-builder/services/aipp-model-center/src/main/java/modelengine/fit/jade/aipp/model/service/UserModelConfig.java
Labels: in: builder, type: feature

#90 [app-builder] 修复已发布应用对话失败问题
  app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/util/CacheUtils.java
Labels: type: bug, in: builder

#91 [app-builder] 增加模型配置表单文件
  examples/app-demo/normal-form/6befc536-7e6d-48b5-8dcb-1c4d04ca4e92/build/index.html
  examples/app-demo/normal-form/6befc536-7e6d-48b5-8dcb-1c4d04ca4e92/build/index.js
  examples/app-demo/normal-form/6befc536-7e6d-48b5-8dcb-1c4d04ca4e92/build/vendors.js
  examples/app-demo/normal-form/6befc536-7e6d-48b5-8dcb-1c4d04ca4e92/build/vendors.js.LICENSE.txt
  examples/app-demo/normal-form/6befc536-7e6d-48b5-8dcb-1c4d04ca4e92/config.json
  examples/app-demo/normal-form/6befc536-7e6d-48b5-8dcb-1c4d04ca4e92/form.png
Labels: type: feature

#94 [app-builder] 增加基础节点：问题优化、问题分类、文本提取
  app-builder/jane/plugins/aipp-plugin/src/main/resources/component/basic_node_en.json
  app-builder/jane/plugins/aipp-plugin/src/main/resources/component/basic_node_zh.json
Labels: in: builder, type: enhancement

#93 [frontend] X86环境EDM知识库repos接口报错信息修改
  app-knowledge/plugins/edm-knowledge/src/main/java/modelengine/jade/knowledge/code/EdmManagerRetCode.java
  app-knowledge/plugins/edm-knowledge/src/main/java/modelengine/jade/knowledge/external/EdmKnowledgeBaseManager.java
  common/plugins/http-interceptor/src/main/resources/i18n/aipp_extension_en.properties
  common/plugins/http-interceptor/src/main/resources/i18n/aipp_extension_zh.properties
Labels: in: builder, type: enhancement

#95 [app-builder] 问界插件适配x86版本
  app-builder/plugins/plugins-show-case-parent/aito-data/plugin.json
  app-builder/plugins/plugins-show-case-parent/aito-data/pom.xml
  app-builder/plugins/plugins-show-case-parent/aito-data/src/main/java/modelengine/fit/jade/aito/data/AITOService.java
  app-builder/plugins/plugins-show-case-parent/aito-data/src/main/java/modelengine/fit/jade/aito/data/AITOServiceImpl.java
  app-builder/plugins/plugins-show-case-parent/aito-data/src/main/resources/data/M5_Exterior_1.jpg
  app-builder/plugins/plugins-show-case-parent/aito-data/src/main/resources/data/M5_Exterior_2.jpg
  app-builder/plugins/plugins-show-case-parent/aito-data/src/main/resources/data/M5_Game.jpg
  app-builder/plugins/plugins-show-case-parent/aito-data/src/main/resources/data/M5_Trim.jpg
  app-builder/plugins/plugins-show-case-parent/aito-data/src/main/resources/data/M7_Exterior_1.jpg
  app-builder/plugins/plugins-show-case-parent/aito-data/src/main/resources/data/M7_Exterior_2.jpg
  app-builder/plugins/plugins-show-case-parent/aito-data/src/main/resources/data/M7_Exterior_3.jpg
  app-builder/plugins/plugins-show-case-parent/aito-data/src/main/resources/data/M7_Front.jpg
  app-builder/plugins/plugins-show-case-parent/aito-data/src/main/resources/data/M7_Seres.jpg
  app-builder/plugins/plugins-show-case-parent/aito-data/src/main/resources/data/M7_Trim_5Seat.jpg
  app-builder/plugins/plugins-show-case-parent/aito-data/src/main/resources/data/M7_Trim_6Seat.jpg
  app-builder/plugins/plugins-show-case-parent/aito-data/src/main/resources/data/M9_Exterior_1.jpg
  app-builder/plugins/plugins-show-case-parent/aito-data/src/main/resources/data/M9_Exterior_2.jpg
  app-builder/plugins/plugins-show-case-parent/aito-data/src/main/resources/data/M9_Trim_5Seat.jpg
  app-builder/plugins/plugins-show-case-parent/aito-data/src/main/resources/data/M9_Trim_6Seat.jpg
  app-builder/plugins/plugins-show-case-parent/aito-data/src/main/resources/data/M9_Trunk.jpg
  app-builder/plugins/plugins-show-case-parent/aito-data/src/main/resources/data/a.txt
  app-builder/plugins/plugins-show-case-parent/aito-data/src/main/resources/data/default.jpg
  app-builder/plugins/plugins-show-case-parent/pom.xml
  app-builder/plugins/plugins-show-case-parent/wenjie-data/src/main/java/modelengine/fit/jade/wenjie/data/WenjieService.java
  app-builder/plugins/plugins-show-case-parent/wenjie-data/src/main/java/modelengine/fit/jade/wenjie/data/WenjieServiceImpl.java
Labels: in: builder, type: enhancement

#89 [app-platform] 应用工程视觉问题交互优化
  app-engine/frontend/src/components/appCard/index.tsx
  app-engine/frontend/src/components/appCard/style.scoped.scss
  app-engine/frontend/src/components/pagination/index.tsx
  app-engine/frontend/src/components/plugin-card/index.tsx
  app-engine/frontend/src/components/plugin-card/style.scss
  app-engine/frontend/src/components/plugin-card/workFlowCard.tsx
  app-engine/frontend/src/components/table-text-search/index.scoped.scss
  app-engine/frontend/src/components/table-text-search/index.tsx
  app-engine/frontend/src/locale/en_US.json
  app-engine/frontend/src/locale/zh_CN.json
  app-engine/frontend/src/pages/addFlow/styles/index.scss
  app-engine/frontend/src/pages/appDetail/analyse/index.tsx
  app-engine/frontend/src/pages/appDetail/analyse/style.scoped.scss
  app-engine/frontend/src/pages/appDetail/feedback/index.tsx
  app-engine/frontend/src/pages/appDetail/feedback/style.scoped.scss
  app-engine/frontend/src/pages/appDetail/index.tsx
  app-engine/frontend/src/pages/appDetail/overview/index.tsx
  app-engine/frontend/src/pages/appDetail/overview/style.scoped.scss
  app-engine/frontend/src/pages/appDetail/style.scoped.scss
  app-engine/frontend/src/pages/appDev/index.scoped.scss
  app-engine/frontend/src/pages/apps/index.scoped.scss
  app-engine/frontend/src/pages/apps/index.tsx
  app-engine/frontend/src/pages/chatPreview/components/history-chat/index.tsx
  app-engine/frontend/src/pages/chatPreview/components/history-chat/style.scoped.scss
  app-engine/frontend/src/pages/chatPreview/styles/chat-details.scss
  app-engine/frontend/src/pages/chatRunning/index.scoped..scss
  app-engine/frontend/src/pages/chatRunning/index.tsx
  app-engine/frontend/src/pages/components/styles/header.scss
  app-engine/frontend/src/pages/plugin/market.tsx
  app-engine/frontend/src/pages/plugin/styles/market.scss
  app-engine/frontend/src/pages/plugin/upload/createWorkflow.tsx
  app-engine/frontend/src/shared/utils/chat.ts
  app-engine/frontend/src/styles/antStyle.scss
Labels: in: builder, type: enhancement

#97 [frontend] 修复无编排应用修改model配置报错问题
  app-engine/frontend/src/pages/configForm/configUi/components/llm.tsx
Labels: type: bug, in: builder

#98 [frontend] 编排节点按钮设置为自适配宽度
  app-engine/frontend/src/pages/addFlow/styles/index.scss
Labels: in: builder, type: enhancement

#102 [frontend] 修改与人工表单通信时机 (#99)
  app-engine/frontend/src/pages/chatPreview/components/receive-box/render.tsx
  examples/app-demo/normal-form/6befc536-7e6d-48b5-8dcb-1c4d04ca4e92/build/index.html
  examples/app-demo/normal-form/6befc536-7e6d-48b5-8dcb-1c4d04ca4e92/build/index.js
  examples/app-demo/normal-form/6befc536-7e6d-48b5-8dcb-1c4d04ca4e92/build/vendors.js
  examples/app-demo/normal-form/6befc536-7e6d-48b5-8dcb-1c4d04ca4e92/form.png
Labels: type: bug, in: builder

#16 [plugin] 添加插件开发指导文档
  doc/Java插件开发指导.md
  doc/Python插件开发指导.md
  doc/images/java插件结构示意图.png
Labels: in: store, type: documentation

#104 [app-builder] 模型表添加唯一约束
  app-builder/plugins/aipp-custom-model-center/src/main/resources/sql/aipp_custom_model_center.sql
Labels: in: builder, type: enhancement

#106 [forntend] 修复应用聊天对话失败问题
  app-engine/frontend/src/index.tsx
  app-engine/frontend/src/pages/chatPreview/components/history-chat/index.tsx
  app-engine/frontend/src/pages/chatPreview/components/send-editor/common/config.ts
  app-engine/frontend/src/pages/chatPreview/components/send-editor/components/file-list.tsx
  app-engine/frontend/src/pages/chatPreview/index.tsx
  app-engine/frontend/src/pages/chatPreview/styles/chat-details.scss
Labels: type: bug, in: builder

#117 [app-builder] 修改插件产物存放目录
  app-builder/fel/java/fel-community/model-openai/pom.xml
  app-builder/fel/java/fel-community/tokenizer-hanlp/pom.xml
  app-builder/fel/java/plugins/fel-langchain-runnable/pom.xml
  app-builder/jane/flow-graph-db-driver/pom.xml
  app-builder/jane/plugins/aipp-plugin/pom.xml
  app-builder/jane/plugins/aipp-websocket-plugin/pom.xml
  app-builder/jane/task-default-driver-jade/pom.xml
  app-builder/jane/task-new/pom.xml
  app-builder/plugins/aipp-classify-question/pom.xml
  app-builder/plugins/aipp-code/pom.xml
  app-builder/plugins/aipp-custom-model-center/pom.xml
  app-builder/plugins/aipp-document-extract-node/pom.xml
  app-builder/plugins/aipp-extractor/pom.xml
  app-builder/plugins/aipp-http-call/pom.xml
  app-builder/plugins/aipp-loop-tool/pom.xml
  app-builder/plugins/aipp-memory/pom.xml
  app-builder/plugins/aipp-model-center-proxy/pom.xml
  app-builder/plugins/aipp-model-center/pom.xml
  app-builder/plugins/aipp-northbound/pom.xml
  app-builder/plugins/aipp-output-formatter/pom.xml
  app-builder/plugins/aipp-prompt-builder/pom.xml
  app-builder/plugins/aipp-rewriter/pom.xml
  app-builder/plugins/aipp-variable-aggregation/pom.xml
  app-builder/plugins/tool-waterflow/pom.xml
  app-builder/plugins/waterflow-appfactory/pom.xml
  app-engine/plugins/app-announcement/pom.xml
  app-engine/plugins/app-base/pom.xml
  app-engine/plugins/app-metrics/pom.xml
  app-engine/plugins/knowledge-base/pom.xml
  app-engine/plugins/voice-text-adapter/pom.xml
  app-eval/plugins/eval-dataset/pom.xml
  app-eval/plugins/eval-task/pom.xml
  app-eval/plugins/simple-uid-generator/pom.xml
  app-image/plugins/image-generator/pom.xml
  app-knowledge/plugins/edm-knowledge/pom.xml
  app-knowledge/plugins/knowledge-i18n/pom.xml
  app-knowledge/plugins/knowledge-manager/pom.xml
  app-knowledge/plugins/knowledge-node-default/pom.xml
  carver/plugins/operation-log-locale/pom.xml
  carver/plugins/telemetry-span-exporter-operation/pom.xml
  carver/plugins/telemetry-span-exporter-repository/pom.xml
  carver/plugins/tool-eco-huggingface/pom.xml
  carver/plugins/tool-eco-langchain/pom.xml
  carver/plugins/tool-eco-llamaindex/pom.xml
  carver/plugins/tool-execution/pom.xml
  carver/plugins/tool-repository-postgresql/pom.xml
  common/plugins/appengine-oms-adapter/pom.xml
  common/plugins/authentication-default/pom.xml
  common/plugins/http-interceptor/pom.xml
  common/plugins/schema-generator/pom.xml
  common/plugins/schema-validator-everit-h1/pom.xml
  store/plugins/store-repository-postgresql/pom.xml
  store/plugins/store-tool-deployer/pom.xml
  store/plugins/store-tool-uploader/pom.xml
Labels: in: builder, type: enhancement

#119 [app-builder] 支持应用的多用户隔离
  app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/condition/AppQueryCondition.java
  app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/controller/AppBuilderAppController.java
  app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/northbound/AppBuilderAppServiceAdapterImpl.java
  app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/service/AppBuilderAppService.java
  app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/service/impl/AppBuilderAppServiceImpl.java
  app-builder/jane/plugins/aipp-plugin/src/main/resources/mapper/AppBuilderAppMapper.xml
  app-builder/jane/plugins/aipp-plugin/src/test/java/modelengine/fit/jober/aipp/service/AppBuilderAppServiceImplTest.java
  app-builder/jane/services/aipp-genericable/src/main/java/modelengine/fit/jober/aipp/genericable/adapter/AppBuilderAppServiceAdapter.java
  app-builder/plugins/aipp-northbound/src/main/java/modelengine/fit/jade/aipp/northbound/controller/AppBuilderAppController.java
Labels: in: builder, type: enhancement

#130 [app-builder] 修复aipp-northbound单测
  app-builder/plugins/aipp-northbound/src/test/java/modelengine/fit/jade/aipp/northbound/controller/AppBuilderAppControllerTest.java
Labels: type: bug, in: builder

#132 [app-builder] 移动 aito 插件到指定目录
  app-builder/plugins/plugins-show-case-parent/aito-data/pom.xml
Labels: in: builder, type: task

#139 [frontend] 修改前端依赖的 elsa 路径
  app-engine/frontend/package.json
Labels: type: bug, in: builder

#142 [frontend] 插件列表问题修复
  app-engine/frontend/src/components/plugin-card/index.tsx
  app-engine/frontend/src/pages/addFlow/components/tool-table.tsx
  app-engine/frontend/src/pages/addFlow/styles/tool-modal.scss
  app-engine/frontend/src/pages/addFlow/styles/tool-table.scss
  app-engine/frontend/src/pages/plugin/market.tsx
Labels: type: bug, in: builder

#144 [plugin] 插件开发文档适配最新插件结构
  doc/Java插件开发指导.md
  doc/Python插件开发指导.md
Labels: in: builder, type: documentation

#147 [frontend] 添加应用复制入口按钮
  app-engine/frontend/src/components/appCard/index.tsx
  app-engine/frontend/src/components/file-upload/index.scoped.scss
  app-engine/frontend/src/components/file-upload/index.tsx
  app-engine/frontend/src/pages/appDev/components/copy-app.tsx
Labels: in: builder, type: feature

#152 [app-builder] 增加elsa-tool-bar的相关翻译
  app-engine/frontend/src/locale/en_US.json
  app-engine/frontend/src/locale/zh_CN.json
Labels: in: builder, type: enhancement

#150 [forntend] 添加工具面板中屏蔽基础节点对应的工具
  app-engine/frontend/src/assets/icon.js
  app-engine/frontend/src/components/icons/base.tsx
  app-engine/frontend/src/locale/en_US.json
  app-engine/frontend/src/locale/zh_CN.json
  app-engine/frontend/src/pages/addFlow/components/basic-item.tsx
  app-engine/frontend/src/pages/addFlow/components/tool-item.tsx
  app-engine/frontend/src/pages/addFlow/components/tool-modal.tsx
  app-engine/frontend/src/pages/chatPreview/index.tsx
  app-engine/frontend/src/pages/components/edit-modal.tsx
Labels: in: builder, type: enhancement

#155 [app-builder] 适配模型对话接口reasoning_content
  app-builder/fel/java/fel-community/model-openai/src/main/java/modelengine/fel/community/model/openai/OpenAiModel.java
  app-builder/fel/java/fel-community/model-openai/src/main/java/modelengine/fel/community/model/openai/entity/chat/OpenAiChatCompletionResponse.java
  app-builder/fel/java/fel-community/model-openai/src/main/java/modelengine/fel/community/model/openai/entity/chat/OpenAiChatMessage.java
  app-builder/fel/java/fel-community/model-openai/src/main/java/modelengine/fel/community/model/openai/enums/ModelProcessingState.java
Labels: type: bug, in: builder

#157 [app-factory] 增加并行执行工具的插件
  app-builder/plugins/aipp-parallel-tool/pom.xml
  app-builder/plugins/aipp-parallel-tool/src/main/java/modelengine/fit/jade/aipp/tool/parallel/domain/BatchRequest.java
  app-builder/plugins/aipp-parallel-tool/src/main/java/modelengine/fit/jade/aipp/tool/parallel/entities/Argument.java
  app-builder/plugins/aipp-parallel-tool/src/main/java/modelengine/fit/jade/aipp/tool/parallel/entities/Config.java
  app-builder/plugins/aipp-parallel-tool/src/main/java/modelengine/fit/jade/aipp/tool/parallel/entities/ToolCall.java
  app-builder/plugins/aipp-parallel-tool/src/main/java/modelengine/fit/jade/aipp/tool/parallel/service/ParallelToolService.java
  app-builder/plugins/aipp-parallel-tool/src/main/java/modelengine/fit/jade/aipp/tool/parallel/service/impl/ParallelToolServiceImpl.java
  app-builder/plugins/aipp-parallel-tool/src/main/java/modelengine/fit/jade/aipp/tool/parallel/support/AippInstanceStatus.java
  app-builder/plugins/aipp-parallel-tool/src/main/java/modelengine/fit/jade/aipp/tool/parallel/support/TaskExecutor.java
  app-builder/plugins/aipp-parallel-tool/src/main/java/modelengine/fit/jade/aipp/tool/parallel/support/impl/AippInstanceStatusImpl.java
  app-builder/plugins/aipp-parallel-tool/src/main/java/modelengine/fit/jade/aipp/tool/parallel/support/impl/DefaultTaskExecutor.java
  app-builder/plugins/aipp-parallel-tool/src/test/java/modelengine/fit/jade/aipp/tool/parallel/domain/BatchRequestTest.java
  app-builder/plugins/pom.xml
Labels: in: builder

#158 [frontend] 文件对话上传添加docx和xlsx类型
  app-engine/frontend/src/pages/chatPreview/components/send-editor/common/config.ts
  app-engine/frontend/src/pages/chatPreview/components/send-editor/components/file-list.tsx
Labels: in: builder, type: enhancement

#161 [appBuilder] 修改知识库配置相关表单，解决流程时序问题
  examples/app-demo/normal-form/17b732c9-5272-42a6-a79d-8d0334a8aa19/build/index.js
Labels: type: bug, in: builder

#162 [app-builder] 应用模板修改
  app-builder/jane/jober/sql/jade/06_appbuilder_insert.sql
Labels: in: builder, type: enhancement

#163 [app-platform] 修改知识库错误码信息
  app-knowledge/plugins/edm-knowledge/src/main/java/modelengine/jade/knowledge/code/EdmManagerRetCode.java
  app-knowledge/services/knowledge-service/src/main/java/modelengine/jade/knowledge/code/KnowledgeManagerRetCode.java
  common/plugins/http-interceptor/src/main/resources/i18n/aipp_extension_en.properties
  common/plugins/http-interceptor/src/main/resources/i18n/aipp_extension_zh.properties
Labels: in: builder, type: enhancement
