Repository ModelEngine-Group/app-platform, pull requests merged in 2025-05, with the labels that each got.

#167 [app-platform] 知识库表创建index语句修改
  app-knowledge/plugins/knowledge-manager/src/main/resources/sql/aipp_user_knowledge.sql
Labels: in: builder, type: enhancement

#168 [app-builder] 应用导出旧数据报错修复
  app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/util/AppImExportUtil.java
Labels: type: bug, in: builder

#169 知识库apiKey处理逻辑修改
  app-knowledge/plugins/knowledge-manager/src/main/java/modelengine/jade/knowledge/service/KnowledgeCenterServiceImpl.java
  app-knowledge/plugins/knowledge-manager/src/main/resources/sql/aipp_user_knowledge.sql
Labels: type: bug, in: builder

#173 修改知识库配置应用问题
  app-builder/jane/jober/sql/jade/06_appbuilder_insert.sql
  app-knowledge/plugins/knowledge-manager/src/main/java/modelengine/jade/knowledge/service/KnowledgeCenterServiceImpl.java
  app-knowledge/plugins/knowledge-manager/src/main/resources/mapper/KnowledgeConfigMapper.xml
  app-knowledge/plugins/knowledge-manager/src/test/java/modelengine/jade/knowledge/service/KnowledgeCenterServiceImplTest.java
  app-knowledge/services/knowledge-service/src/main/java/modelengine/jade/knowledge/code/KnowledgeManagerRetCode.java
  common/plugins/http-interceptor/src/main/resources/i18n/aipp_extension_en.properties
  common/plugins/http-interceptor/src/main/resources/i18n/aipp_extension_zh.properties
  examples/app-demo/normal-form/17b732c9-5272-42a6-a79d-8d0334a8aa19/build/index.js
Labels: type: bug, in: builder

#177 接入知识库功能优化
  app-knowledge/plugins/qianfan-knowledge/pom.xml
  app-knowledge/plugins/qianfan-knowledge/src/test/java/modelengine/jade/knowledge/MockedQianfanKnowledgeBaseInnerController.java
  app-knowledge/plugins/qianfan-knowledge/src/test/java/modelengine/jade/knowledge/MockedQianfanKnowledgeListQueryParam.java
  app-knowledge/plugins/qianfan-knowledge/src/test/java/modelengine/jade/knowledge/MockedQianfanRetrievalParam.java
  app-knowledge/plugins/qianfan-knowledge/src/test/java/modelengine/jade/knowledge/QianfanKnowledgeBaseManagerTest.java
  app-knowledge/plugins/qianfan-knowledge/src/test/java/modelengine/jade/knowledge/QianfanRepoServiceImplTest.java
  app-knowledge/plugins/qianfan-knowledge/src/test/resources/listRepoResult.json
  app-knowledge/plugins/qianfan-knowledge/src/test/resources/retrieveResult.json
  examples/app-demo/normal-form/17b732c9-5272-42a6-a79d-8d0334a8aa19/build/index.js
  examples/app-demo/normal-form/17b732c9-5272-42a6-a79d-8d0334a8aa19/build/vendors.js
Labels: in: builder, type: enhancement

#182 [frontend] 使用elsa导出的i18n文件
  app-engine/frontend/src/locale/i18n.ts
Labels: in: builder, type: enhancement

#185 [app-builder] 增加 README 文件的 ELSA 编译产物链接
  README.md
Labels: in: builder, type: documentation

#180 [app-builder] 并行节点特性添加
  app-builder/jane/plugins/aipp-plugin/src/main/resources/application-prod.yml
  app-builder/jane/plugins/aipp-plugin/src/main/resources/component/basic_node_en.json
  app-builder/jane/plugins/aipp-plugin/src/main/resources/component/basic_node_zh.json
  app-builder/plugins/aipp-parallel-tool/pom.xml
  app-builder/plugins/aipp-parallel-tool/src/main/java/modelengine/fit/jade/aipp/tool/parallel/domain/BatchRequest.java
  app-builder/plugins/aipp-parallel-tool/src/main/java/modelengine/fit/jade/aipp/tool/parallel/entities/ToolCall.java
  app-builder/plugins/aipp-parallel-tool/src/main/java/modelengine/fit/jade/aipp/tool/parallel/service/impl/ParallelToolServiceImpl.java
  app-builder/plugins/aipp-parallel-tool/src/main/resources/sql/data/aipp_parallel_tool.sql
  app-builder/plugins/aipp-parallel-tool/src/test/java/modelengine/fit/jade/aipp/tool/parallel/domain/BatchRequestTest.java
  app-engine/frontend/src/locale/en_US.json
  app-engine/frontend/src/locale/zh_CN.json
  app-engine/frontend/src/pages/addFlow/components/elsa-stage.tsx
Labels: in: builder, type: feature

#186 [app-builder] 并行节点数据库语句拷贝
  shell/sql_build.sh
Labels: in: builder, type: task

#188 [app-builder] ci: add develop branch trigger
  .github/workflows/app-platform-java-compile.yml
Labels: in: builder, type: task

#189 [app-platform] bugfix in knowledge base feature
  app-builder/jane/jober/sql/jade/06_appbuilder_insert.sql
  app-engine/frontend/src/pages/addFlow/components/connect-knowledge.tsx
  app-engine/frontend/src/pages/addFlow/components/elsa-stage.tsx
  app-engine/frontend/src/pages/configForm/configUi/components/add-knowledge.tsx
  app-engine/frontend/src/pages/configForm/configUi/components/add-search.tsx
  app-engine/frontend/src/pages/configForm/configUi/components/knowledge-container.tsx
  app-engine/frontend/src/pages/configForm/configUi/components/knowledge.tsx
  app-engine/frontend/src/shared/http/appBuilder.ts
  app-engine/frontend/src/shared/http/knowledge.ts
  app-knowledge/plugins/knowledge-manager/src/main/java/modelengine/jade/knowledge/condition/KnowledgeConfigQueryCondition.java
  app-knowledge/plugins/knowledge-manager/src/main/java/modelengine/jade/knowledge/controller/KnowledgeController.java
  app-knowledge/plugins/knowledge-manager/src/main/java/modelengine/jade/knowledge/po/KnowledgeConfigPo.java
  app-knowledge/plugins/knowledge-manager/src/main/java/modelengine/jade/knowledge/service/KnowledgeCenterServiceImpl.java
  app-knowledge/plugins/knowledge-manager/src/main/resources/mapper/KnowledgeConfigMapper.xml
  app-knowledge/plugins/knowledge-manager/src/main/resources/sql/aipp_user_knowledge.sql
  app-knowledge/plugins/knowledge-manager/src/test/java/modelengine/jade/knowledge/KnowledgeControllerTest.java
  app-knowledge/plugins/knowledge-manager/src/test/java/modelengine/jade/knowledge/service/KnowledgeCenterServiceImplTest.java
  app-knowledge/plugins/knowledge-node-default/src/main/java/modelengine/jade/knowledge/entity/RetrieverServiceOption.java
  app-knowledge/plugins/knowledge-node-default/src/main/java/modelengine/jade/knowledge/service/RetrieverService.java
  app-knowledge/plugins/knowledge-node-default/src/main/java/modelengine/jade/knowledge/service/impl/RetrieverServiceImpl.java
  app-knowledge/plugins/knowledge-node-default/src/test/java/modelengine/jade/knowledge/RetrieverServiceTest.java
  app-knowledge/services/knowledge-service/src/main/java/modelengine/jade/knowledge/KnowledgeCenterService.java
  app-knowledge/services/knowledge-service/src/main/java/modelengine/jade/knowledge/dto/KnowledgeConfigDto.java
Labels: type: bug, in: builder

#190 adapt to changes in Qianfan interface response
  app-knowledge/plugins/knowledge-manager/src/test/java/modelengine/jade/knowledge/KnowledgeControllerTest.java
  app-knowledge/plugins/qianfan-knowledge/src/main/java/modelengine/jade/knowledge/entity/QianfanKnowledgeEntity.java
  app-knowledge/plugins/qianfan-knowledge/src/main/java/modelengine/jade/knowledge/entity/QianfanKnowledgeListEntity.java
Labels: type: bug, in: builder

#191 Modify the front-end update logic for the knowledge base graph data
  app-engine/frontend/src/pages/configForm/configUi/components/knowledge-container.tsx
Labels: type: bug, in: builder

#195 [appBuilder] 去掉无用的import引入
  app-knowledge/plugins/knowledge-manager/src/test/java/modelengine/jade/knowledge/KnowledgeControllerTest.java
Labels: type: bug, in: builder

#176 [app-builder] 新增模型配置表单
  app-builder/builtin/form/model-config-form/.gitignore
  app-builder/builtin/form/model-config-form/.npmrc
  app-builder/builtin/form/model-config-form/README.md
  app-builder/builtin/form/model-config-form/config.json
  app-builder/builtin/form/model-config-form/form.png
  app-builder/builtin/form/model-config-form/package.json
  app-builder/builtin/form/model-config-form/src/app.tsx
  app-builder/builtin/form/model-config-form/src/assets/images/empty.png
  app-builder/builtin/form/model-config-form/src/components/form.tsx
  app-builder/builtin/form/model-config-form/src/context/index.ts
  app-builder/builtin/form/model-config-form/src/index.tsx
  app-builder/builtin/form/model-config-form/src/styles/form.scss
  app-builder/builtin/form/model-config-form/src/utils/index.ts
  app-builder/builtin/form/model-config-form/webpack.common.js
  app-builder/builtin/form/model-config-form/webpack.dev.js
  app-builder/builtin/form/model-config-form/webpack.prod.js
Labels: in: builder, type: enhancement

#203 [appBuilder] 增加国际化未翻译的报错信息
  app-builder/jane/plugins/aipp-plugin/src/main/resources/i18n/messages_en.properties
Labels: in: builder, type: enhancement

#202 [frontend] 修复工具流创建、发布问题
  app-engine/frontend/src/pages/addFlow/components/addflow-header.tsx
  app-engine/frontend/src/pages/components/publish-modal.tsx
  app-engine/frontend/src/pages/plugin/upload/createWorkflow.tsx
  app-engine/frontend/src/shared/http/aipp.ts
Labels: type: bug, in: builder

#204 [app-builder] 添加 DB 数据定時清理机制
  app-builder/jane/plugins/aipp-plugin/pom.xml
  app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/mapper/AippChatMapper.java
  app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/mapper/AippLogMapper.java
  app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/mapper/AppBuilderRuntimeInfoMapper.java
  app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/repository/AippChatRepository.java
  app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/repository/AippInstanceLogRepository.java
  app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/repository/AppBuilderRuntimeInfoRepository.java
  app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/repository/impl/AippChatRepositoryImpl.java
  app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/repository/impl/AippInstanceLogRepositoryImpl.java
  app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/repository/impl/AppBuilderRuntimeInfoRepositoryImpl.java
  app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/service/scheduletask/AippInstanceLogCleaner.java
  app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/service/scheduletask/AppBuilderDbCleanScheduler.java
  app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/service/scheduletask/AppBuilderRuntimeInfoCleaner.java
  app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/service/scheduletask/ChatSessionCleaner.java
  app-builder/jane/plugins/aipp-plugin/src/main/java/modelengine/fit/jober/aipp/service/scheduletask/CsvWriterHelper.java
  app-builder/jane/plugins/aipp-plugin/src/main/resources/application-prod.yml
  app-builder/jane/plugins/aipp-plugin/src/main/resources/mapper/AippChatMapper.xml
  app-builder/jane/plugins/aipp-plugin/src/main/resources/mapper/AippLogMapper.xml
  app-builder/jane/plugins/aipp-plugin/src/main/resources/mapper/AppBuilderRuntimeInfoMapper.xml
  app-builder/jane/plugins/aipp-plugin/src/test/java/modelengine/fit/jober/aipp/repository/impl/AippInstanceLogRepositoryImplTest.java
  app-builder/jane/plugins/aipp-plugin/src/test/java/modelengine/fit/jober/aipp/repository/impl/AppBuilderRuntimeInfoRepositoryImplTest.java
  app-builder/jane/plugins/aipp-plugin/src/test/java/modelengine/fit/jober/aipp/service/scheduletask/AippInstanceLogCleanerTest.java
  app-builder/jane/plugins/aipp-plugin/src/test/java/modelengine/fit/jober/aipp/service/scheduletask/ChatSessionCleanerTest.java
  app-builder/jane/plugins/aipp-plugin/src/test/resources/sql/clear_table.sql
  app-builder/jane/plugins/aipp-plugin/src/test/resources/sql/init.sql
  app-builder/jane/task-new/pom.xml
  app-builder/jane/task-new/src/main/java/modelengine/fit/task_new/MetaInstanceServiceImpl.java
  app-builder/jane/task-new/src/main/java/modelengine/fit/task_new/mapper/MetaInstanceMapper.java
  app-builder/jane/task-new/src/main/java/modelengine/fit/task_new/repository/MetaInstanceRepository.java
  app-builder/jane/task-new/src/main/java/modelengine/fit/task_new/repository/impl/MetaInstanceRepositoryImpl.java
  app-builder/jane/task-new/src/main/resources/application-prod.yml
  app-builder/jane/task-new/src/main/resources/mapper/MetaInstanceMapper.xml
  app-builder/waterflow/java/waterflow-service/src/main/resources/application.yml
  app-knowledge/plugins/edm-knowledge/src/test/java/modelengine/jade/knowledge/EdmKnowledgeBaseManagerTest.java
  common/dependency/pom.xml
Labels: in: builder, type: enhancement
